### PR TITLE
Scripts before DQM presentation

### PR DESCRIPTION
**Pull request by amandeephy**

### CODE REVIEW

**Comment by mmusich** [comment]
@gbenelli @sroychow @arossi83 should this be merged?

**Comment by gbenelli** [comment]
Hi Marco,
We're still figuring out the best way to proceed for LPC TRK DQM group internal code review. I posted these comments to Amandeep's fork commits (as a test!) and did not realize they would show up here, so sorry for the noise. On the other hand I was thinking that we would indeed use the TRK DPG organization to handle the code review (via PRs from individual developers). Would this be too noisy for everyone and should we instead use our own sub-organization? The actual code here could be a first commit but we going to re-organize it in order to use functions across files via import statements instead of executing each script with popen statements.

**Comment by mmusich** [comment]
I have no particular opinion on how you internally organize the review process. If you want to do it here is fine. 
Now do I understand correctly that this version of the code is superseded?
The only thing I'd like to ask you is to keep it tidy. If you want to build the changes on top of this one I will merge it. If instead this is to be discarded please close it.
In case it is only for discussion please use the keyword RFC in the PR title so the repo managers are aware of your intentions.
Thanks

**Comment by sroychow** [comment]
@amandeephy Could you add instructions on how to test the scripts? Please mention which CMSSW version you used for the tests.

**Comment by amandeephy** [comment]
Hello @sroychow, sorry I was not notified about this message.
Yes I have updated the instructions for using these scripts :)

**Pull request merged**
